// This code automatically generated by TableCodeGen
using UnityEngine;
using System.Collections;
using System.Collections.Generic;

public class shop_groupTable
{
	public class Row
	{
		public string groupId;
		public string stageMin;
		public string stageMax;
		public string shopType;
		public string groupRate;
		public string id;
		public string resType;
		public string resId;
		public string resNumber;
		public string moneyType;
		public string moneyValue;
		public string rate;
		public string stock;
		public string enable;

	}

}