#if UNITY_EDITOR
namespace Zitga.CsvTools
{
    public static class TableCodeGen
    {
        const string CodeTemplate = @"// This code automatically generated by TableCodeGen
using UnityEngine;
using System.Collections;
using System.Collections.Generic;

public class $CLASS : ScriptableObject
{
	public class Row
	{
$ROW_MEMBER_CODE
	}

}";

        public static string Generate(string csvText, string className)
        {
            if (string.IsNullOrEmpty(csvText))
                return null;

            string[][] grid = CsvParser2.Parse(csvText);
            if (grid.Length < 1)
                return null;

            string rowMemberCode = "";
            for (int i = 0; i < grid[0].Length; i++)
            {
                rowMemberCode += $"\t\tpublic string {StringUtils.ConvertSnakeCaseToCamelCase(grid[0][i])};\n";
            }

            string code = CodeTemplate;
            code = code.Replace("$CLASS", className);
            code = code.Replace("$ROW_MEMBER_CODE", rowMemberCode);

            return code;
        }
    }
}
#endif